In [1]:
import numpy as np

In [2]:
x = np.arange(64).reshape(8, 8)
print(x)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [3]:
scaling = 2
splits = 8//scaling
x = np.split(x, splits, 1)
print(x)

[array([[ 0,  1],
       [ 8,  9],
       [16, 17],
       [24, 25],
       [32, 33],
       [40, 41],
       [48, 49],
       [56, 57]]), array([[ 2,  3],
       [10, 11],
       [18, 19],
       [26, 27],
       [34, 35],
       [42, 43],
       [50, 51],
       [58, 59]]), array([[ 4,  5],
       [12, 13],
       [20, 21],
       [28, 29],
       [36, 37],
       [44, 45],
       [52, 53],
       [60, 61]]), array([[ 6,  7],
       [14, 15],
       [22, 23],
       [30, 31],
       [38, 39],
       [46, 47],
       [54, 55],
       [62, 63]])]


In [4]:
x = np.mean(x, 2)
print(x)

[[ 0.5  8.5 16.5 24.5 32.5 40.5 48.5 56.5]
 [ 2.5 10.5 18.5 26.5 34.5 42.5 50.5 58.5]
 [ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]
 [ 6.5 14.5 22.5 30.5 38.5 46.5 54.5 62.5]]


In [5]:
x = np.split(x, splits, 1)
print(x)

[array([[ 0.5,  8.5],
       [ 2.5, 10.5],
       [ 4.5, 12.5],
       [ 6.5, 14.5]]), array([[16.5, 24.5],
       [18.5, 26.5],
       [20.5, 28.5],
       [22.5, 30.5]]), array([[32.5, 40.5],
       [34.5, 42.5],
       [36.5, 44.5],
       [38.5, 46.5]]), array([[48.5, 56.5],
       [50.5, 58.5],
       [52.5, 60.5],
       [54.5, 62.5]])]


In [6]:
x = np.average(x, 2)
print(x)

[[ 4.5  6.5  8.5 10.5]
 [20.5 22.5 24.5 26.5]
 [36.5 38.5 40.5 42.5]
 [52.5 54.5 56.5 58.5]]
